### ISSUE TITLE
Config file for builders

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#158]
This is something @asraa proposed in the past but I'm not able to find the issue, so creating this one.

We currently hardcode builders. It's fine to have a pre-defined list, but would be great to let users define their own too.

Two (complimentary) options:
1. Add a `--builder` option
2. Use config file, e.g.:

```yaml
version: 1
builders:
  - name: GCB_level2 # Arbitrary name selected by users
    specs: https://slsa.dev/provenance/v0.1 # Maybe this should be a global option instead of for each builder
    id: https://cloudbuild.googleapis.com/GoogleHostedWorker@v0.2 # See https://cloud.google.com/build/docs/securing-builds/view-build-provenance
    levels: # As per https://slsa.dev/spec/v0.1/requirements
      - Provenance: 2
      - Build: 2
   
  - name: GH_generic_level3
    specs: https://slsa.dev/provenance/v0.1
    id: https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/generator_generic_slsa3.yml
    levels: # As per https://slsa.dev/spec/v0.1/requirements
      - Provenance: 3
      - Build: 2

  - name: GHA_Go_level3
    specs: https://slsa.dev/provenance/v0.1
    id: https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/builder_go_slsa3.yml
    levels: # As per https://slsa.dev/spec/v0.1/requirements
      - Provenance: 3
      - Build: 3
```

We can also let users use both the config and CLI option, e.g., `--builders GHA_Go_level3`

These options could be hidden behind a `SLSA_VERIFIER_EXPERIMENTAL` env variable to let us toy with the idea.

Note that in the config file above, we could leave levels aside for the first implementation and only focus on the `name` and `id` fields. 

Later when we have more insights in https://github.com/slsa-framework/slsa-verifier/issues/84, we can integrate the requirement options, e.g., `--builder XXX --requirements "xxx"`. The builder provides a baseline of requirements, so the requirement could be just the difference in this case. TBD.

What do you think of starting with `name` and `id` (and `specs`?) fields for a v0?

@joshuagl @asraa @ianlewis
