### ISSUE TITLE
Support for GCB provenance

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#181]
See https://cloud.google.com/build/docs/securing-builds/view-build-provenance

We need to decide what provenance input file we take as input:
1. The full result of the command above:
```
image_summary:
  digest: sha256:370938421b670a1489b98adac2ad41709bf0892be36382d50d563868dbfa5b16
  fully_qualified_digest: us-central1-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE@sha256:HASH
  registry: us-central1-docker.pkg.dev
  repository: REPOSITORY
provenance_summary:
  provenance:
  - build:
  ...
```
2. Or just the `.payload` part.
3. Both, because users make mistakes

Verification will work roughly as follows:
1. Use the keyid field to look up a hard-coded key. There are keys for each region, so we need to download them all ahead of time and add pre-submits to check whether some new regions have been created. (Note: keyid looks like `projects/verified-builder/locations/<region>/keyRings/attestor/cryptoKeys/builtByGCB/cryptoKeyVersions/1`)
2. Verify the signature using hardcoded key
3. Verify the builder is `https://cloudbuild.googleapis.com/GoogleHostedWorker@vX`. X depends on the SLSA levels. 0.2 is SLSA 2.
4. Verify `fileHash` is same as `digest.sha256`
5. Verify source. ~~Bucket does no work well yet. Building with `gs://bucketname/source.zip` gave:
`gs://bucketname_cloudbuild/source/1659399946.445909-f440f71d9f054ecc8476c4c5ec39b465.zip#1659399946910830"` in materials,  and:
```
"sourceProvenance": {
          "resolvedStorageSource": {
            "bucket": "bucketname_cloudbuild",
            "object": "source/1659399946.445909-f440f71d9f054ecc8476c4c5ec39b465.zip",
            "generation": "1659399946910830"
          },
```
in a custom field. **Update**: let's not support bucket since it does not meet the "version control" requirement. 

I'll update this issue once I have tried building from a repository.

We are also going to need a `--builder` option to differentiate between builders. Having short names like `GCB_level3` and `GHA_generic_level3`, etc could be useful. Maybe we could do that as part of https://github.com/slsa-framework/slsa-verifier/issues/158? Suggestions welcome.

It may also be useful to support provenance directly from stdin:
```
gcloud ... --show-provenance | slsa-verifier ...
```

I'll see if the team is interested in storing the provenance along the image on the registry (like cosign does): that would be a usability improvement.
