### ISSUE TITLE
remove setuo-go from the codeql-analysis workflow

### ISSUE THREAD

**Issue by ramonpetgrave64** [slsa-framework/slsa-verifier#740]
Remove setuo-go from the codeql-analysis.yml workflow.
https://github.com/slsa-framework/slsa-verifier/pull/738#discussion_r1462446238

We have added a custom step to the code-ql analysys job, as a workaround to fix the workflow when using go1.21. 
This issue is a reminder that we should reconsider having that custom step. 

```
      - name: setup-go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: "go.mod"
          # not needed but gets ride of warnings
          cache: false

```
